# TODO: comment
macro(add_plugin _NAME)
  add_library(${_NAME} MODULE ${ARGN})
  target_link_libraries(${_NAME} ${LIBS})
  message(STATUS "name: ${_NAME}")
  set(PLUGIN_NAME ${_NAME})
  set(PLUGIN_PATH ${LIBRARY_OUTPUT_PATH})
  set_target_properties(${PLUGIN_NAME} PROPERTIES DEFINE_SYMBOL "DIET_EXPORTS")
  configure_file(${CMAKE_CURRENT_SOURCE_DIR}/${PLUGIN_NAME}.xml.in ${MANIFEST_OUTPUT_PATH}/${PLUGIN_NAME}.xml)
endmacro()
